import {
  AlertTriangle,
  BrainCircuit,
  CheckCircle2,
  Download,
  FileJson2,
  FileText,
  Gauge,
  ScanText,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { DocumentInsight, ExtractionResult } from "@/lib/types";
import { cn } from "@/lib/utils";

interface Props {
  extraction: ExtractionResult;
  insight: DocumentInsight;
}

function buildMarkdownReport(
  extraction: ExtractionResult,
  insight: DocumentInsight,
): string {
  const lines = [
    `# Document Review: ${extraction.filename}`,
    `\n**Document Type:** ${insight.document_type}`,
    `**Confidence:** ${insight.confidence}`,
    `\n## Summary\n${insight.summary}`,
    `\n## Important Dates`,
    ...insight.important_dates.map((date) => `- ${date}`),
    `\n## Required Documents`,
    ...insight.required_documents.map((document) => `- ${document}`),
    `\n## Fees & Amounts`,
    ...insight.fees_and_amounts.map((fee) => `- ${fee}`),
    `\n## Action Items`,
    ...insight.action_items.map((action) => `- ${action}`),
    `\n## Risks`,
    ...insight.risks.map(
      (risk) =>
        `- **[${risk.priority.toUpperCase()}]** ${risk.issue}: ${risk.why_it_matters}`,
    ),
    `\n---\n*Generated by Papervault — local processing only. This is not professional advice.*`,
  ];
  return lines.join("\n");
}

function download(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function EvidenceTab({ extraction, insight }: Props) {
  const basename = extraction.filename.replace(/\.[^.]+$/, "");

  return (
    <div className="space-y-4">
      <div className="grid gap-4 lg:grid-cols-2">
        <DiagnosticCard
          icon={<ScanText size={18} />}
          title="Extraction quality"
          confidence={extraction.diagnostics.confidence}
          score={extraction.diagnostics.confidence_score}
          metadata={[
            `Engine: ${extraction.diagnostics.engine}`,
            extraction.diagnostics.is_ocr
              ? `OCR: ${extraction.diagnostics.ocr_engine ?? "local"}`
              : "Direct text extraction",
            extraction.diagnostics.ocr_mean_confidence !== null
              ? `OCR mean confidence: ${formatPercent(extraction.diagnostics.ocr_mean_confidence)}`
              : null,
          ].filter((item): item is string => Boolean(item))}
          signals={extraction.diagnostics.signals}
          recommendations={extraction.diagnostics.recommendations}
        />
        <DiagnosticCard
          icon={<BrainCircuit size={18} />}
          title="Analysis confidence"
          confidence={insight.confidence}
          score={insight.analysis_diagnostics.confidence_score}
          metadata={[
            `Classification: ${insight.analysis_diagnostics.classification_confidence}`,
            `${insight.analysis_diagnostics.extracted_signal_count} structured signals`,
            `${insight.analysis_diagnostics.grounded_field_count} grounded finding groups`,
          ]}
          signals={insight.analysis_diagnostics.reasons}
          recommendations={insight.limitations}
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-[minmax(17rem,0.35fr)_minmax(0,1fr)]">
        <Card className="h-fit">
        <CardHeader className="px-5 pb-2 pt-5">
          <span className="flex size-10 items-center justify-center rounded-xl bg-accent/10 text-accent">
            <Download size={18} />
          </span>
          <CardTitle className="pt-2 text-base font-semibold">Export this review</CardTitle>
          <p className="text-xs leading-5 text-muted-foreground">
            Save the structured findings in a readable report or machine-friendly format.
          </p>
        </CardHeader>
        <CardContent className="space-y-2 px-5 pb-5 pt-3">
          <Button
            variant="outline"
            className="w-full justify-start"
            onClick={() =>
              download(
                buildMarkdownReport(extraction, insight),
                `${basename}-review.md`,
                "text/markdown",
              )
            }
          >
            <FileText />
            Download Markdown
          </Button>
          <Button
            variant="outline"
            className="w-full justify-start"
            onClick={() =>
              download(
                JSON.stringify({ extraction, insight }, null, 2),
                `${basename}-review.json`,
                "application/json",
              )
            }
          >
            <FileJson2 />
            Download JSON
          </Button>
          <div className="flex items-start gap-2 border-t border-border/70 pt-4 text-[0.7rem] leading-5 text-muted-foreground">
            <ShieldCheck size={13} className="mt-0.5 shrink-0 text-emerald-600" />
            Exports are created in your browser and are not uploaded.
          </div>
        </CardContent>
        </Card>

        <Card className="min-w-0">
        <CardHeader className="flex-row items-start justify-between space-y-0 px-5 pb-3 pt-5">
          <div>
            <CardTitle className="text-base font-semibold">Extracted evidence</CardTitle>
            <p className="mt-1 text-xs text-muted-foreground">
              Inspect the text used to produce this review.
            </p>
          </div>
          {extraction.content_available && (
            <span className="hidden rounded-full bg-muted px-2.5 py-1 text-[0.68rem] text-muted-foreground sm:inline-flex">
              {extraction.word_count.toLocaleString()} words
            </span>
          )}
        </CardHeader>
        <CardContent className="px-5 pb-5">
          {extraction.content_available ? (
            <>
              <textarea
                readOnly
                aria-label="Extracted document text"
                value={extraction.extracted_text}
                className="scrollbar-subtle h-[28rem] w-full resize-y rounded-xl border border-border bg-muted/25 px-4 py-3 font-mono text-xs leading-5 text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
              <p className="mt-3 text-xs leading-5 text-muted-foreground">
                {extraction.word_count.toLocaleString()} words ·{" "}
                {extraction.char_count.toLocaleString()} characters · extracted via{" "}
                {extraction.extraction_method}
              </p>
            </>
          ) : (
            <div className="flex min-h-[22rem] flex-col items-center justify-center rounded-xl border border-dashed border-border bg-muted/20 px-6 text-center">
              <span className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <ShieldCheck size={21} />
              </span>
              <p className="mt-4 text-sm font-semibold text-foreground">
                Source text was not retained
              </p>
              <p className="mt-2 max-w-sm text-xs leading-5 text-muted-foreground">
                This saved review keeps structured results without the original
                document text. Re-upload the document to inspect its evidence.
              </p>
            </div>
          )}
        </CardContent>
        </Card>
      </div>
    </div>
  );
}

function DiagnosticCard({
  icon,
  title,
  confidence,
  score,
  metadata,
  signals,
  recommendations,
}: {
  icon: React.ReactNode;
  title: string;
  confidence: "high" | "medium" | "low";
  score: number;
  metadata: string[];
  signals: string[];
  recommendations: string[];
}) {
  const tone = {
    high: {
      icon: "bg-emerald-500/10 text-emerald-600",
      badge: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400",
      bar: "bg-emerald-500",
    },
    medium: {
      icon: "bg-amber-500/10 text-amber-600",
      badge: "bg-amber-500/10 text-amber-700 dark:text-amber-400",
      bar: "bg-amber-500",
    },
    low: {
      icon: "bg-destructive/10 text-destructive",
      badge: "bg-destructive/10 text-destructive",
      bar: "bg-destructive",
    },
  }[confidence];

  return (
    <Card className="min-w-0">
      <CardHeader className="flex-row items-start justify-between space-y-0 px-5 pb-3 pt-5">
        <div className="flex items-start gap-3">
          <span className={cn("flex size-10 items-center justify-center rounded-xl", tone.icon)}>
            {icon}
          </span>
          <div>
            <CardTitle className="text-sm font-semibold">{title}</CardTitle>
            <p className="mt-1 text-xs text-muted-foreground">
              Explainable local quality assessment
            </p>
          </div>
        </div>
        <span className={cn("rounded-full px-2.5 py-1 text-[0.68rem] font-medium capitalize", tone.badge)}>
          {confidence}
        </span>
      </CardHeader>
      <CardContent className="space-y-4 px-5 pb-5">
        <div>
          <div className="flex items-center justify-between text-xs">
            <span className="flex items-center gap-1.5 text-muted-foreground">
              <Gauge size={12} />
              Confidence score
            </span>
            <span className="font-semibold text-foreground">{formatPercent(score)}</span>
          </div>
          <div className="mt-2 h-2 overflow-hidden rounded-full bg-muted">
            <div
              className={cn("h-full rounded-full transition-all", tone.bar)}
              style={{ width: `${Math.max(2, score * 100)}%` }}
            />
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {metadata.map((item) => (
            <span
              key={item}
              className="rounded-full border border-border bg-muted/35 px-2.5 py-1 text-[0.65rem] text-muted-foreground"
            >
              {item}
            </span>
          ))}
        </div>

        {signals.length > 0 && (
          <div>
            <p className="flex items-center gap-1.5 text-xs font-medium text-foreground">
              <CheckCircle2 size={13} className="text-emerald-600" />
              Confidence signals
            </p>
            <ul className="mt-2 space-y-1.5 text-xs leading-5 text-muted-foreground">
              {signals.map((signal) => (
                <li key={signal} className="flex items-start gap-2">
                  <span className="mt-2 size-1 shrink-0 rounded-full bg-accent" />
                  {signal}
                </li>
              ))}
            </ul>
          </div>
        )}

        {recommendations.length > 0 && (
          <div className="rounded-xl border border-amber-500/20 bg-amber-500/[0.05] p-3">
            <p className="flex items-center gap-1.5 text-xs font-medium text-foreground">
              <AlertTriangle size={13} className="text-amber-600" />
              Verification guidance
            </p>
            <ul className="mt-2 space-y-1.5 text-xs leading-5 text-muted-foreground">
              {recommendations.map((recommendation) => (
                <li key={recommendation}>• {recommendation}</li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function formatPercent(value: number) {
  return `${Math.round(value * 100)}%`;
}
