/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Extracted Document
         * @description Analyze already-extracted text and return grounded structured insights.
         */
        post: operations["analyze_extracted_document_documents_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Document
         * @description Answer a question using local retrieval over provided document text.
         */
        post: operations["ask_document_documents_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Document Checklist
         * @description Generate an action checklist and risk panel from extracted document text.
         */
        post: operations["create_document_checklist_documents_checklist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Document
         * @description Extract text from an uploaded document without storing the original file.
         */
        post: operations["extract_document_documents_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a minimal health response for smoke checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intelligence/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Intelligence Runtime
         * @description Return configured local model, embedding, and vector runtime diagnostics.
         */
        get: operations["intelligence_runtime_intelligence_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sessions
         * @description Return recent session metadata for the history page.
         */
        get: operations["get_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Save privacy-preserving local session history.
         */
        post: operations["create_session_sessions_post"];
        /**
         * Clear Sessions
         * @description Delete every saved session and its Q&A history. Local-only, no recovery.
         */
        delete: operations["clear_sessions_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Return saved structured results and optional explicitly retained text.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeRequest
         * @description Request body for analyzing already-extracted document text.
         */
        AnalyzeRequest: {
            /**
             * Filename
             * @description Optional source filename.
             */
            filename?: string | null;
            /**
             * Text
             * @description Extracted document text to analyze.
             */
            text: string;
        };
        /**
         * AnswerExplanation
         * @description Human-readable basis for an answer and its confidence.
         */
        AnswerExplanation: {
            /** Confidence Reasons */
            confidence_reasons?: string[];
            /** Limitations */
            limitations?: string[];
            /**
             * Strategy
             * @default no_answer
             */
            strategy: string;
        };
        /**
         * AskRequest
         * @description Request body for local document question answering.
         */
        AskRequest: {
            /**
             * Answer Mode
             * @description Preferred answer mode. Local LLM mode still falls back safely.
             * @default auto
             * @enum {string}
             */
            answer_mode: "auto" | "extractive" | "local_llm";
            /**
             * Filename
             * @description Optional source filename.
             */
            filename?: string | null;
            /**
             * Model
             * @description Optional installed Ollama model override for this question.
             */
            model?: string | null;
            /**
             * Question
             * @description Question to answer from the document.
             */
            question: string;
            /**
             * Text
             * @description Extracted document text to search.
             */
            text: string;
            /**
             * Top K
             * @description Number of chunks to retrieve.
             * @default 5
             */
            top_k: number;
        };
        /** Body_extract_document_documents_extract_post */
        Body_extract_document_documents_extract_post: {
            /** File */
            file: string;
        };
        /**
         * ChecklistItem
         * @description Actionable checklist item derived from grounded document insights.
         */
        ChecklistItem: {
            /**
             * Due Date
             * @description Associated due date if known.
             */
            due_date?: string | null;
            /**
             * Priority
             * @description high, medium, or low.
             */
            priority: string;
            /**
             * Reason
             * @description Why this task matters.
             */
            reason: string;
            /**
             * Source Snippet
             * @description Source text that supports this task.
             */
            source_snippet?: string | null;
            /**
             * Status
             * @description Checklist status.
             * @default pending
             */
            status: string;
            /**
             * Title
             * @description Short action title.
             */
            title: string;
        };
        /**
         * ChecklistResult
         * @description Checklist and risk panel generated from document insights.
         */
        ChecklistResult: {
            /**
             * Guidance
             * @description User-facing guidance for the checklist result.
             */
            guidance: string;
            /** Items */
            items?: components["schemas"]["ChecklistItem"][];
            /** Risks */
            risks?: components["schemas"]["RiskPanelItem"][];
        };
        /**
         * ClassificationResult
         * @description Deterministic document classification result.
         */
        ClassificationResult: {
            /**
             * Confidence
             * @description low, medium, or high.
             */
            confidence: string;
            /**
             * Document Type
             * @description Best matching document category.
             */
            document_type: string;
            /**
             * Evidence
             * @description Document snippets that supported classification.
             */
            evidence?: string[];
        };
        /**
         * DocumentAnalysisDiagnostics
         * @description Signals used to explain document-analysis confidence.
         */
        DocumentAnalysisDiagnostics: {
            /**
             * Classification Confidence
             * @default low
             */
            classification_confidence: string;
            /**
             * Confidence Score
             * @default 0
             */
            confidence_score: number;
            /**
             * Extracted Signal Count
             * @default 0
             */
            extracted_signal_count: number;
            /**
             * Grounded Field Count
             * @default 0
             */
            grounded_field_count: number;
            /** Reasons */
            reasons?: string[];
        };
        /**
         * DocumentInsight
         * @description Structured document insights derived from extracted text.
         */
        DocumentInsight: {
            /** Action Items */
            action_items?: string[];
            /** @description Document classification. */
            classification: components["schemas"]["ClassificationResult"];
            /**
             * Confidence
             * @description Overall extraction confidence.
             */
            confidence: string;
            /** Contact Information */
            contact_information?: string[];
            diagnostics?: components["schemas"]["DocumentAnalysisDiagnostics"];
            /** Fees Or Amounts */
            fees_or_amounts?: components["schemas"]["ExtractedItem"][];
            /** Important Dates */
            important_dates?: components["schemas"]["ExtractedItem"][];
            /** Limitations */
            limitations?: string[];
            /** Missing Information */
            missing_information?: string[];
            official_notice?: components["schemas"]["OfficialNoticeBreakdown"] | null;
            /** Required Documents */
            required_documents?: string[];
            /** Risks */
            risks?: components["schemas"]["RiskInsight"][];
            /**
             * Summary
             * @description Short extractive summary.
             */
            summary: string;
            /**
             * Title
             * @description Likely document title.
             */
            title?: string | null;
        };
        /**
         * ExtractedItem
         * @description A grounded extracted value with optional source text.
         */
        ExtractedItem: {
            /**
             * Source Snippet
             * @description Nearby source text from the document.
             */
            source_snippet?: string | null;
            /**
             * Value
             * @description Extracted value.
             */
            value: string;
        };
        /**
         * ExtractionDiagnostics
         * @description Explainable quality assessment for locally extracted text.
         */
        ExtractionDiagnostics: {
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
            /**
             * Confidence
             * @description low, medium, or high.
             * @default low
             */
            confidence: string;
            /**
             * Confidence Score
             * @description Normalized extraction quality score.
             * @default 0
             */
            confidence_score: number;
            /**
             * Engine
             * @description Extraction or OCR engine used.
             * @default unknown
             */
            engine: string;
            /**
             * Is Ocr
             * @description Whether OCR produced the text.
             * @default false
             */
            is_ocr: boolean;
            /**
             * Ocr Engine
             * @description OCR engine name when used.
             */
            ocr_engine?: string | null;
            /**
             * Ocr Mean Confidence
             * @description Mean OCR token confidence when the engine exposes it.
             */
            ocr_mean_confidence?: number | null;
            /**
             * Page Text Coverage
             * @description Share of pages containing meaningful text.
             */
            page_text_coverage?: number | null;
            /**
             * Readable Character Ratio
             * @default 0
             */
            readable_character_ratio: number;
            /** Recommendations */
            recommendations?: string[];
            /** Signals */
            signals?: string[];
            /**
             * Suspicious Character Ratio
             * @default 0
             */
            suspicious_character_ratio: number;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
        };
        /**
         * ExtractionError
         * @description Structured extraction error suitable for user-facing feedback.
         */
        ExtractionError: {
            /**
             * Code
             * @description Stable machine-readable error code.
             */
            code: string;
            /**
             * Message
             * @description Human-readable error message.
             */
            message: string;
        };
        /**
         * ExtractionResult
         * @description Result of extracting text from a document without interpretation.
         */
        ExtractionResult: {
            diagnostics?: components["schemas"]["ExtractionDiagnostics"];
            /**
             * Document Type
             * @description Document extension without leading dot.
             */
            document_type: string;
            /** @description Structured error when extraction could not complete. */
            error?: components["schemas"]["ExtractionError"] | null;
            /**
             * Filename
             * @description Source filename.
             */
            filename: string;
            /**
             * Metadata
             * @description Local extraction metadata.
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Page Count
             * @description Number of pages when known.
             */
            page_count?: number | null;
            /**
             * Text
             * @description Clean extracted text.
             */
            text: string;
            /**
             * Warnings
             * @description Non-fatal warnings.
             */
            warnings?: string[];
        };
        /**
         * GenerationDiagnostics
         * @description Explain which local answer generator ran and whether fallback occurred.
         */
        GenerationDiagnostics: {
            /**
             * Actual Mode
             * @default extractive
             */
            actual_mode: string;
            /** Configured Model */
            configured_model?: string | null;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /**
             * Local Llm Enabled
             * @default false
             */
            local_llm_enabled: boolean;
            /** Model Used */
            model_used?: string | null;
            /**
             * Requested Mode
             * @default auto
             */
            requested_mode: string;
        };
        /**
         * HealthResponse
         * @description Response model for backend health checks.
         */
        HealthResponse: {
            /**
             * App
             * @description Application name.
             */
            app: string;
            /**
             * Status
             * @description Service status.
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntelligenceRuntimeResponse
         * @description Local intelligence runtime configuration and availability.
         */
        IntelligenceRuntimeResponse: {
            /** Available Models */
            available_models?: components["schemas"]["LocalModelInfo"][];
            /**
             * Configured Model
             * @description Default configured Ollama model.
             */
            configured_model: string;
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Embedding Provider
             * @description Configured local embedding provider.
             */
            embedding_provider: string;
            /**
             * Local Llm Enabled
             * @description Whether local LLM use is enabled.
             */
            local_llm_enabled: boolean;
            /**
             * Ollama Available
             * @description Whether the configured Ollama runtime responded.
             */
            ollama_available: boolean;
            /**
             * Status Message
             * @description Plain-language local runtime status.
             */
            status_message: string;
            /**
             * Vector Backend
             * @description Available vector-search backend.
             */
            vector_backend: string;
        };
        /**
         * LocalModelInfo
         * @description Installed model reported by the local Ollama runtime.
         */
        LocalModelInfo: {
            /** Modified At */
            modified_at?: string | null;
            /**
             * Name
             * @description Ollama model name.
             */
            name: string;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /**
         * OfficialNoticeBreakdown
         * @description Domain-specific breakdown for government notices and gazette notifications.
         */
        OfficialNoticeBreakdown: {
            /** Compliance Duties */
            compliance_duties?: string[];
            /**
             * Confidence
             * @description low, medium, or high.
             * @default low
             */
            confidence: string;
            /** Consequences */
            consequences?: string[];
            /** Effective Timing */
            effective_timing?: string | null;
            /** Gazette Date */
            gazette_date?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Issuing Authority */
            issuing_authority?: string | null;
            /** Legal Basis */
            legal_basis?: string | null;
            /** Limitations */
            limitations?: string[];
            /** Notice Number */
            notice_number?: string | null;
            /** Notice Type */
            notice_type?: string | null;
            /** Payment Timing */
            payment_timing?: string | null;
            /** Subject */
            subject?: string | null;
            /** Table Rows */
            table_rows?: components["schemas"]["OfficialNoticeTableRow"][];
        };
        /**
         * OfficialNoticeTableRow
         * @description Structured row recovered from an official notice table.
         */
        OfficialNoticeTableRow: {
            /**
             * Heading
             * @description Schedule heading or code.
             */
            heading?: string | null;
            /**
             * Liable Party
             * @description Person or party made liable.
             */
            liable_party?: string | null;
            /**
             * Rate Or Amount
             * @description Rate, fee, or amount.
             */
            rate_or_amount?: string | null;
            /**
             * Service
             * @description Taxable service or subject.
             */
            service?: string | null;
            /**
             * Source Snippet
             * @description Grounding source text.
             */
            source_snippet?: string | null;
        };
        /**
         * QuestionAnswer
         * @description Grounded answer produced from local document retrieval.
         */
        QuestionAnswer: {
            /**
             * Answer
             * @description Answer grounded in source snippets.
             */
            answer: string;
            /**
             * Confidence
             * @description low, medium, or high.
             */
            confidence: string;
            explanation?: components["schemas"]["AnswerExplanation"];
            generation?: components["schemas"]["GenerationDiagnostics"];
            /**
             * Mode
             * @description Answering mode, such as extractive or local_llm.
             */
            mode: string;
            retrieval?: components["schemas"]["RetrievalDiagnostics"];
            /** Source Snippets */
            source_snippets?: components["schemas"]["SourceSnippet"][];
        };
        /**
         * RetrievalDiagnostics
         * @description Explain how document chunks were selected for an answer.
         */
        RetrievalDiagnostics: {
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Embedding Provider
             * @default unknown
             */
            embedding_provider: string;
            /** Matched Terms */
            matched_terms?: string[];
            /**
             * Mean Score
             * @default 0
             */
            mean_score: number;
            /** Query Terms */
            query_terms?: string[];
            /**
             * Relevant Count
             * @default 0
             */
            relevant_count: number;
            /**
             * Requested Top K
             * @default 0
             */
            requested_top_k: number;
            /**
             * Retrieved Count
             * @default 0
             */
            retrieved_count: number;
            /**
             * Score Spread
             * @default 0
             */
            score_spread: number;
            /**
             * Top Score
             * @default 0
             */
            top_score: number;
            /**
             * Vector Backend
             * @default python
             */
            vector_backend: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * RiskInsight
         * @description Carefully worded possible risk grounded in document text.
         */
        RiskInsight: {
            /**
             * Confidence
             * @description low, medium, or high.
             */
            confidence: string;
            /**
             * Issue
             * @description Possible issue, not a definitive conclusion.
             */
            issue: string;
            /**
             * Source Snippet
             * @description Grounding snippet.
             */
            source_snippet?: string | null;
            /**
             * Suggested Verification
             * @description Recommended verification step.
             */
            suggested_verification: string;
            /**
             * Why It Matters
             * @description Plain-language reason to verify it.
             */
            why_it_matters: string;
        };
        /**
         * RiskPanelItem
         * @description Risk panel item with careful non-advisory wording.
         */
        RiskPanelItem: {
            /**
             * Confidence Level
             * @description low, medium, or high.
             */
            confidence_level: string;
            /**
             * Possible Issue
             * @description Possible issue found in the document.
             */
            possible_issue: string;
            /**
             * Source Snippet
             * @description Grounding source text.
             */
            source_snippet?: string | null;
            /**
             * Suggested Verification Step
             * @description Suggested verification step.
             */
            suggested_verification_step: string;
            /**
             * Why It Matters
             * @description Why the user should verify it.
             */
            why_it_matters: string;
        };
        /**
         * SavedSession
         * @description Saved session with structured outputs and Q&A history.
         */
        SavedSession: {
            /** @description Generated checklist and risk panel. */
            checklist: components["schemas"]["ChecklistResult"];
            /**
             * Content Stored
             * @description Whether raw extracted text was explicitly retained for this session.
             * @default false
             */
            content_stored: boolean;
            /**
             * Created At
             * @description UTC creation timestamp.
             */
            created_at: string;
            /**
             * Document Type
             * @description Classified document type.
             */
            document_type: string;
            /**
             * Extracted Text
             * @description Raw extracted text when local full-content history is explicitly enabled.
             */
            extracted_text?: string | null;
            /**
             * Extracted Text Hash
             * @description SHA-256 hash of extracted text.
             */
            extracted_text_hash: string;
            /**
             * Filename
             * @description Source filename.
             */
            filename: string;
            /** @description Structured document insight. */
            insight: components["schemas"]["DocumentInsight"];
            /** Qa History */
            qa_history?: components["schemas"]["QuestionAnswer"][];
            /**
             * Session Id
             * @description Local session identifier.
             */
            session_id: string;
            /**
             * Text Preview
             * @description Always None unless explicitly configured later.
             */
            text_preview?: string | null;
        };
        /**
         * SaveSessionRequest
         * @description Request body for saving a document review session from the frontend.
         */
        SaveSessionRequest: {
            /** @description Full checklist to persist for reload. */
            checklist: components["schemas"]["ChecklistResult"];
            /**
             * Document Type
             * @description Classified document type.
             */
            document_type: string;
            /**
             * Extracted Text
             * @description Extracted text used for hashing. It is retained only when PAPERVAULT_STORE_EXTRACTED_TEXT is explicitly enabled.
             */
            extracted_text: string;
            /**
             * Filename
             * @description Source filename.
             */
            filename: string;
            /** @description Full document insight to persist for reload. */
            insight: components["schemas"]["DocumentInsight"];
        };
        /**
         * SessionCreatedResponse
         * @description Response returned after saving a local review session.
         */
        SessionCreatedResponse: {
            /**
             * Id
             * @description Created local session identifier.
             */
            id: string;
        };
        /**
         * SessionMetadata
         * @description Privacy-preserving metadata for a saved local document session.
         */
        SessionMetadata: {
            /**
             * Content Stored
             * @description Whether raw extracted text was explicitly retained for this session.
             * @default false
             */
            content_stored: boolean;
            /**
             * Created At
             * @description UTC creation timestamp.
             */
            created_at: string;
            /**
             * Document Type
             * @description Classified document type.
             */
            document_type: string;
            /**
             * Extracted Text Hash
             * @description SHA-256 hash of extracted text.
             */
            extracted_text_hash: string;
            /**
             * Filename
             * @description Source filename.
             */
            filename: string;
            /**
             * Session Id
             * @description Local session identifier.
             */
            session_id: string;
            /**
             * Text Preview
             * @description Always None unless explicitly configured later.
             */
            text_preview?: string | null;
        };
        /**
         * SessionsClearedResponse
         * @description Response returned after clearing local review history.
         */
        SessionsClearedResponse: {
            /**
             * Deleted
             * @description Whether the local history clear completed.
             */
            deleted: boolean;
        };
        /**
         * SourceSnippet
         * @description Source snippet used to ground an answer.
         */
        SourceSnippet: {
            /**
             * Chunk Id
             * @description Source chunk identifier.
             */
            chunk_id: string;
            /**
             * Page Number
             * @description Source page number if known.
             */
            page_number?: number | null;
            /**
             * Score
             * @description Retrieval similarity score.
             */
            score: number;
            /**
             * Source Filename
             * @description Source filename if known.
             */
            source_filename?: string | null;
            /**
             * Text
             * @description Source text snippet.
             */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_extracted_document_documents_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInsight"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_document_documents_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_checklist_documents_checklist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_document_documents_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_document_documents_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    intelligence_runtime_intelligence_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceRuntimeResponse"];
                };
            };
        };
    };
    get_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMetadata"][];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_sessions_sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsClearedResponse"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
